# Generated by Django 5.1.2 on 2024-10-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('Country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufactured_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='Products')),
            ],
        ),
    ]
