# Generated by Django 5.1.2 on 2024-10-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.TextField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Confirm', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
