# Generated by Django 5.1.2 on 2024-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_cartdb_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Price',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
